CONFIG = {
    'data_path': './data/food.parquet',

    'folder_process': './data/processed',

    'folder_output': './output',

    'data_clean': './data/processed/nutrient_cleaned.parquet',

    'target': 'nutriscore_score',

    'selected_var': [
        'nutriments',
        # 'nutriscore_grade',
        'nutriscore_score',
        'product_name',
        'categories_tags', 
        'food_groups_tags',
        'brands_tags', 
        'countries_tags',
        ],

    'selected_nutrient': [
        'energy-kcal',
        'energy-kj',
        'fat', 
        'saturated-fat', 
        'sugars', 
        'proteins', 
        'salt', 
        'fiber', 
        'fruits-vegetables-nuts'
        ],

    'feats_model': [
        'fat', 
        'saturated-fat', 
        'sugars', 
        'proteins', 
        'salt', 
        'fiber', 
        'fruits-vegetables-nuts',
        'is_fats_nuts_seeds',
        'energy-kcal-revise',
        # 'tag_0',
        # 'tag2_0'
        ],

    'beverage_tag': {
        'en:alcoholic-beverages',
        'en:fruit-nectars',
        'en:teas-and-herbal-teas-and-coffees',
        'en:waters-and-flavored-waters',
        'en:fruit-juices',
        'en:artificially-sweetened-beverages',
        # 'en:plant-based-milk-substitutes',
        'en:sweetened-beverages',
        'en:unsweetened-beverages',
        'en:beverages',
        },

    'fats_nuts_seeds': {
        'en:nuts',
        'en:seeds',
        'en:oilseeds',
        'en:nut-butters',
        'en:seed-butters',
        'en:fats'
        },

    'nutrient_limit': {
        'salt': (0, 20),
        'energy-kcal': (0, 1000),
        'fat': (0, 100),
        'sugars': (0, 90),
        'proteins': (0, 80),
        'saturated-fat': (0, 80),
        'fiber': (0, 50),
        'fruits-vegetables-nuts': (0, 100)
        },

    'seed': 21,

    # 'lgb_best_params': {
    #     'num_leaves': 71, 
    #     'max_depth': 8, 
    #     'learning_rate': 0.19555730155532078, 
    #     'n_estimators': 799, 
    #     'min_child_samples': 23, 
    #     'subsample': 0.82869949009953, 
    #     'colsample_bytree': 0.8013705255983335,
    #     'force_col_wise': True
    #     },  # 2

    'lgb_best_params': {
        'num_leaves': 78, 
        'max_depth': 8, 
        'learning_rate': 0.18787646650018355, 
        'n_estimators': 763, 
        'min_child_samples': 6, 
        'subsample': 0.7640731824942187, 
        'colsample_bytree': 0.9861965567938009,
        'force_col_wise': True
        },  # 3

    'knn_gridsrch': {
        'knn__n_neighbors': [3, 5, 9],  # bas = surapprentissage, haut = lissage +
        'knn__weights': ['uniform', 'distance'],
        'knn__p': [1, 2],  # 1 = manhattan, 2 = euclidean
    },

    'algo': {
        'A': [0],
        'B': [1, 2],
        'C': [3, 10],
        'D': [11, 18],
        'E': [19]
    },

    'algo_fatnutseed': {
        'A': [-6],
        'B': [-5, 2]
    },

}

CAT_CUSTOM = {

    'dairy_products': [
        'en:milk-and-yogurt',
        'en:cheese',
        'en:dairy-desserts',
        'en:milk-and-dairy-products',
        'en:plant-based-milk-substitutes'
        ],

    'cereals': [
        'en:bread',
        'en:breakfast-cereals',
        'en:cereals',
        'en:potatoes',
        'en:cereals-and-potatoes',
        'en:nuts'
    ],

    'meat_fish_eggs': [
        'en:meat-other-than-poultry',
        'en:poultry',
        'en:processed-meat',
        'en:meat',
        'en:offals',
        'en:lean-fish',
        'en:fatty-fish',
        'en:fish-and-seafood',
        'en:eggs',
        'en:fish-meat-eggs'
    ],

    'fruits_vege_legumes': [
        'en:fruits',
        'en:vegetables',
        'en:dried-fruits',
        'en:legumes',
        'en:fruits-and-vegetables'
    ],

    'salty_snacks_sauces': [
        'en:salty-and-fatty-products',
        'en:fats',
        'en:appetizers',
        'en:salty-snacks',
        'en:dressings-and-sauces',
        'en:fats-and-sauces'
    ],

    'sweet_desserts': [
        'en:pastries',
        'en:sweets',
        'en:biscuits-and-cakes',
        'en:chocolate-products',
        'en:sugary-snacks'
    ],

    'processed_food': [
        'en:soups',
        'en:one-dish-meals',
        'en:sandwiches',
        'en:pizza-pies-and-quiches',
        'en:composite-foods'
    ]

    }

CAT2_CUSTOM = {
    'fish_eafood': [
        "en:anchovy",
        "en:cods",
        "en:sardines-in-olive-oil",
        "en:mussels",
        "en:preparations-made-from-fish-meat",
        "en:breaded-fish",
        "en:smoked-salmons",
        "en:tunas-in-oil",
        "en:canned-sardines",
        "en:fish-rillettes",
        "en:smoked-fishes",
        "en:fish-fillets",
        "en:fish-preparations",
        "en:frozen-seafood",
        "en:seafood",
        "en:salmons",
        "en:canned-tunas",
        "en:crustaceans",
        "en:shrimps",
        "en:mollusc"
        ],
        
    'meat': [
        "en:ground-beef-steaks",
        "en:beef-steaks",
        "en:beef-preparations",
        "en:beef-dishes",
        "en:beef-and-its-products",
        "en:beef",
        "en:pork-roasts",
        "en:chorizo",
        "en:raw-cured-ham",
        "en:pork-meals",
        "en:pork-pates",
        "en:pork-and-its-products",
        "en:pork",
        "en:duck-dishes",
        "en:turkey-cutlets",
        "en:turkeys",
        "en:turkey-and-its-products",
        "en:chicken-thighs",
        "en:chicken-nuggets",
        "en:chickens",
        "en:chicken-preparations",
        "en:chicken-and-its-products",
        "en:cooked-chicken",
        "en:cooked-poultries",
        "en:poultries",
        "en:poultry-sausages",
        "en:poultry-meals",
        "en:poultry-hams",
        "en:spanish-meat-products",
        "en:italian-meat-products",
        "en:french-sausages",
        "en:dried-meats",
        "en:offals",
        "en:tripe-dishes",
        "en:serrano-ham",
        "en:country-terrines",
        "en:potted-meats",
        "en:white-meat-rillettes",
        "en:rillettes",
        "en:terrines",
        "en:prepared-meats",
        "en:meat-preparations",
        "en:meat-analogues",
        "en:salami",
        "en:meals-with-meat",
        "en:meals-with-chicken",
        "en:meats",
        "en:meats-and-their-products",
        "en:ducks",
        "en:whole-foies-gras-from-ducks",
        "en:foies-gras-from-ducks",
        "en:foies-gras"
        ],
    
    'dairy_and_egg' : [
        "en:free-range-chicken-eggs",
        "en:chicken-eggs",
        "en:eggs",
        "en:fromages-blancs-petit-suisses-and-skyr",
        "en:camemberts",
        "en:skyrs",
        "en:parmigiano-reggiano",
        "en:unpasteurised-cheeses",
        "en:blue-veined-cheeses",
        "en:cheeses-from-england",
        "en:cheeses-from-the-united-kingdom",
        "en:cheeses-of-the-netherlands",
        "en:french-cheeses",
        "en:italian-cheeses",
        "en:pasteurized-cheeses",
        "en:soft-cheeses",
        "en:soft-cheeses-with-bloomy-rind",
        "en:hard-cheeses",
        "en:gouda",
        "en:comte",
        "en:emmentaler",
        "en:mozzarella",
        "en:cream-cheeses",
        "en:cheese-spreads",
        "en:grated-cheese",
        "en:cheddar-cheese",
        "en:sheep-s-milk-cheeses",
        "en:goat-cheeses",
        "en:fresh-cheeses",
        "en:cow-cheeses",
        "en:cheeses",
        "en:fermented-creams",
        "en:bifidus-yogurts",
        "en:flavoured-yogurts",
        "en:stirred-yogurts",
        "en:cow-milk-yogurts",
        "en:greek-style-yogurts",
        "en:plain-yogurts",
        "en:fruit-yogurts",
        "en:yogurts",
        "en:flavoured-fermented-dairy-desserts",
        "en:fermented-dairy-desserts",
        "en:fermented-dairy-desserts-with-fruits",
        "en:fermented-milk-products",
        "en:fermented-foods",
        "en:quarks",
        "en:milks-liquid-and-powder",
        "en:whole-milks",
        "en:semi-skimmed-milks",
        "en:homogenized-milks",
        "en:cow-milks",
        "en:uht-milks",
        "en:milks",
        "en:dairies",
        "en:dairy-substitutes",
        "en:dairy-spreads",
        "en:butters",
        "en:margarines",
        "en:animal-fats",
        "en:milkfat",
        "en:spreadable-fats"
        ],

    'vegetable' : [
        "en:pumpkin-and-squash-plant-products",
        "en:white-beans",
        "en:mountain-products",
        "en:corn",
        "en:green-peas",
        "en:mixed-vegetables",
        "en:dried-vegetables",
        "en:canned-tomatoes",
        "en:tomatoes",
        "en:carrots",
        "en:green-beans",
        "en:asparagus",
        "en:onions-and-their-products",
        "en:potatoes",
        "en:fries",
        "en:frozen-fried-potatoes",
        "en:potato-crisps-in-sunflower-oil",
        "en:potato-gnocchi",
        "en:gnocchi",
        "en:canned-common-beans",
        "en:common-beans",
        "en:chickpeas",
        "en:lentils",
        "en:green-olives",
        "en:pitted-olives",
        "en:olives",
        "en:pickled-cucumbers",
        "en:gherkins",
        "en:pickled-vegetables",
        "en:pickles",
        "en:legumes",
        "en:vegetables",
        "en:fresh-vegetables",
        "en:prepared-vegetables",
        "en:frozen-vegetables",
        "en:legumes-and-their-products",
        "en:vegetables-based-foods",
        "en:leaf-vegetables",
        "en:vegetable-rods",
        "en:vegetable-soups",
        "en:cream-of-vegetable-soups",
        "en:vegetable-fats",
        "en:mushrooms",
        "en:mushrooms-and-their-products",
        "en:plant-based-pickles"
        ],
    
    'fruit' : [
        "en:purees",
        "en:raspberry-jams",
        "en:citrus-jams",
        "en:apricot-jams",
        "en:strawberry-jams",
        "en:marmalades",
        "en:jams",
        "en:berry-jams",
        "en:fruits-in-syrup",
        "en:fruits",
        "en:tropical-fruits",
        "en:dried-fruits",
        "en:canned-fruits",
        "en:fruits-and-vegetables-based-foods",
        "en:fruits-based-foods",
        "en:apple-compotes",
        "en:compotes",
        "en:dates",
        "en:berries"
        ],

    'cereal_and_pasta' : [
        "en:dry-durum-wheat-pasta",
        "en:wheat-semolinas",
        "en:canned-cereals",
        "en:corn-flakes",
        "en:extruded-flakes",
        "en:cereal-semolinas",
        "en:cereal-flakes",
        "en:rolled-flakes",
        "en:rolled-oats",
        "en:cereal-bars",
        "en:breakfast-cereals",
        "en:cereals-with-fruits",
        "en:chocolate-cereals",
        "en:cereals-and-their-products",
        "en:cereal-pastas",
        "en:durum-wheat-pasta",
        "en:indica-rices",
        "en:basmati-rices",
        "en:aromatic-rices",
        "en:long-grain-rices",
        "en:rices",
        "en:quinoa",
        "en:spaghetti",
        "en:penne",
        "en:tortellini",
        "en:ravioli",
        "en:egg-pastas",
        "en:fresh-pasta",
        "en:noodles",
        "en:stuffed-pastas",
        "en:pasta-sauces",
        "en:pasta-dishes",
        "en:dry-pastas",
        "en:wheat-flours",
        "en:cereal-flours",
        "en:flours"
        ],

    'bakery_bread' : [
        "en:wheat-flatbreads",
        "en:bakery-products",
        "en:hamburger-buns",
        "en:baguettes",
        "en:special-breads",
        "en:sliced-breads",
        "en:toasts",
        "en:wholemeal-breads",
        "en:white-breads",
        "en:wheat-breads",
        "en:breads",
        "en:flatbreads",
        "en:croissants",
        "en:brioches",
        "en:viennoiseries",
        "en:waffles",
        "en:crepes-and-galettes",
        "en:crepes",
        "en:rusks",
        "en:madeleines",
        "en:doughnuts",
        "en:muffins",
        "en:pie-dough",
        "en:pastry-helpers",
        "en:chocolate-croissant",
        "en:pate",
        "en:stuffed-wafers",
        "en:wafers",
        "en:breadsticks",
        "en:puffed-rice-cakes",
        "en:puffed-cereal-cakes",
        "en:crackers-appetizers",
        "en:dry-biscuits",
        "en:chocolate-biscuits",
        "en:filled-biscuits",
        "en:bars-covered-with-chocolate",
        "en:drop-cookies",
        "en:gingerbreads",
        "en:sweet-pies",
        "en:panettone",
        "en:cakes",
        "en:sweet-pastries-and-pies",
        "en:pies",
        "en:salted-pies",
        "en:pastries",
        "en:pizzas",
        "en:cheese-pizzas",
        "en:vegetarian-pizzas",
        "en:frozen-pizzas",
        "en:frozen-pizzas-and-pies",
        "en:pizzas-pies-and-quiches",
        "en:gratins"
        ],

    'snacks_and_sweets' : [
        "en:salted-snacks",
        "en:potato-crisps",
        "en:flavoured-potato-crisps",
        "en:corn-chips",
        "en:crisps",
        "en:popcorn",
        "en:salted-nuts",
        "en:roasted-nuts",
        "en:shelled-nuts",
        "en:cashew-nuts",
        "en:pistachios",
        "en:peanuts",
        "en:almonds",
        "en:walnuts",
        "en:nuts",
        "en:nuts-and-their-products",
        "en:sunflower-seeds",
        "en:sunflower-seeds-and-their-products",
        "en:legume-seeds",
        "en:bonbons",
        "en:candies",
        "en:chocolate-candies",
        "en:assorted-chocolate-candies",
        "en:candy-chocolate-bars",
        "en:gummi-candies",
        "en:caramels",
        "en:nougats",
        "en:turron",
        "en:chocolates",
        "en:milk-chocolates",
        "en:white-chocolates",
        "en:dark-chocolates",
        "en:chocolates-with-hazelnuts",
        "en:chocolate-eggs",
        "en:chocolate-molds",
        "en:chocolate-cakes",
        "en:chocolate-desserts",
        "en:chocolate-spreads",
        "en:cocoa-and-hazelnuts-spreads",
        "en:hazelnut-spreads",
        "en:chocolate-cereals",
        "en:bars",
        "en:chocolate-bars",
        "en:filled-chocolates",
        "en:confectioneries",
        "en:sweet-spreads",
        "en:sweet-fritters",
        "en:sorbets",
        "en:ice-creams",
        "en:ice-cream-bars",
        "en:ice-creams-and-sorbets",
        "en:frozen-desserts",
        "en:ice-cream-tubs"
        ],

    'meals_and_condiments' : [
        "en:puff-pastry-meals",
        "en:combination-meals",
        "en:refrigerated-meals",
        "en:fresh-meals",
        "en:microwave-meals",
        "en:prepared-salads",
        "en:meals-with-fish",
        "en:meals-with-chicken",
        "en:meals-with-meat",
        "en:meals",
        "en:frozen-ready-made-meals",
        "en:frozen-meals",
        "en:frozen-foods",
        "en:reheatable-soups",
        "en:canned-meals",
        "en:prepared-lasagne",
        "en:cooking-helpers",
        "en:broths",
        "en:soups",
        "en:vegetable-soups",
        "en:cream-soups",
        "en:canned-soups",
        "en:meal-sauces",
        "en:hot-sauces",
        "en:ketchup",
        "en:mayonnaises",
        "en:salad-dressings",
        "en:pestos",
        "en:green-pestos",
        "en:soy-sauces",
        "en:condiments",
        "en:mustards",
        "en:tomato-sauces",
        "en:tomatoes-and-their-products"
        ],
        
    'supplements_and_sweeteners' : [
        "en:coffees",
        "en:bodybuilding-supplements",
        "en:dietary-supplements",
        "en:honeys",
        "en:bee-products",
        "en:syrups",
        "en:simple-syrups",
        "en:sweeteners"
        ],

    'plant_based_products' : [
        "en:vegan-products",
        "en:tofu",
        "en:plant-based-meals",
        "en:vegetarian-patties",
        "en:meat-alternatives",
        "en:plant-based-foods",
        "en:plant-based-foods-and-beverages",
        "en:fresh-plant-based-foods",
        "en:frozen-plant-based-foods",
        "en:dried-plant-based-foods",
        "en:plant-based-spreads",
        "en:legume-butters",
        "en:non-dairy-yogurts",
        "en:non-dairy-desserts",
        "en:non-dairy-fermented-foods",
        "en:dairy-substitutes"
        ]

}